<a href="https://colab.research.google.com/github/swgu931/temp/blob/master/DE_course_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

문제 설명
배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하려 합니다.

예를 들어 array가 [1, 5, 2, 6, 3, 7, 4], i = 2, j = 5, k = 3이라면

1. array의 2번째부터 5번째까지 자르면 [5, 2, 6, 3]입니다.
2. 1에서 나온 배열을 정렬하면 [2, 3, 5, 6]입니다.
3. 2에서 나온 배열의 3번째 숫자는 5입니다.
배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, commands의 모든 원소에 대해 앞서 설명한 연산을 적용했을 때 나온 결과를 배열에 담아 return 하도록 solution 함수를 작성해주세요.

제한사항
array의 길이는 1 이상 100 이하입니다.
array의 각 원소는 1 이상 100 이하입니다.
commands의 길이는 1 이상 50 이하입니다.
commands의 각 원소는 길이가 3입니다.
입출력 예
array	commands	return
[1, 5, 2, 6, 3, 7, 4]	[[2, 5, 3], [4, 4, 1], [1, 7, 3]]	[5, 6, 3]
입출력 예 설명
[1, 5, 2, 6, 3, 7, 4]를 2번째부터 5번째까지 자른 후 정렬합니다. [2, 3, 5, 6]의 세 번째 숫자는 5입니다.
[1, 5, 2, 6, 3, 7, 4]를 4번째부터 4번째까지 자른 후 정렬합니다. [6]의 첫 번째 숫자는 6입니다.
[1, 5, 2, 6, 3, 7, 4]를 1번째부터 7번째까지 자릅니다. [1, 2, 3, 4, 5, 6, 7]의 세 번째 숫자는 3입니다.

In [0]:
list = [1, 5, 2, 6, 3, 7, 4]

commands = [[2,5,3],[4,4,1],[1,7,3]]




https://programmers.co.kr/learn/courses/30/lessons/42576

문제 설명

수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다.

마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.

제한사항
마라톤 경기에 참여한 선수의 수는 1명 이상 100,000명 이하입니다.
completion의 길이는 participant의 길이보다 1 작습니다.
참가자의 이름은 1개 이상 20개 이하의 알파벳 소문자로 이루어져 있습니다.
참가자 중에는 동명이인이 있을 수 있습니다.
입출력 예
participant	completion	return
[leo, kiki, eden]	[eden, kiki]	leo
[marina, josipa, nikola, vinko, filipa]	[josipa, filipa, marina, nikola]	vinko
[mislav, stanko, mislav, ana]	[stanko, ana, mislav]	mislav
입출력 예 설명
예제 #1
leo는 참여자 명단에는 있지만, 완주자 명단에는 없기 때문에 완주하지 못했습니다.

예제 #2
vinko는 참여자 명단에는 있지만, 완주자 명단에는 없기 때문에 완주하지 못했습니다.

예제 #3
mislav는 참여자 명단에는 두 명이 있지만, 완주자 명단에는 한 명밖에 없기 때문에 한명은 완주하지 못했습니다.

In [0]:
participant = 
completion = 

members = {}
for i in participant:
    if i not in members: members[1] = 1
    else: members[1] += 1
members

for i in completion:
    if i in members: members[i] -= 1
membeers

for key, value in members.items():
      if value > 0 : print(key)

https://programmers.co.kr/learn/courses/30/lessons/17681

비밀지도
네오는 평소 프로도가 비상금을 숨겨놓는 장소를 알려줄 비밀지도를 손에 넣었다. 그런데 이 비밀지도는 숫자로 암호화되어 있어 위치를 확인하기 위해서는 암호를 해독해야 한다. 다행히 지도 암호를 해독할 방법을 적어놓은 메모도 함께 발견했다.

지도는 한 변의 길이가 n인 정사각형 배열 형태로, 각 칸은 공백(" ) 또는벽(#") 두 종류로 이루어져 있다.
전체 지도는 두 장의 지도를 겹쳐서 얻을 수 있다. 각각 지도 1과 지도 2라고 하자. 지도 1 또는 지도 2 중 어느 하나라도 벽인 부분은 전체 지도에서도 벽이다. 지도 1과 지도 2에서 모두 공백인 부분은 전체 지도에서도 공백이다.
지도 1과 지도 2는 각각 정수 배열로 암호화되어 있다.
암호화된 배열은 지도의 각 가로줄에서 벽 부분을 1, 공백 부분을 0으로 부호화했을 때 얻어지는 이진수에 해당하는 값의 배열이다.
secret map

네오가 프로도의 비상금을 손에 넣을 수 있도록, 비밀지도의 암호를 해독하는 작업을 도와줄 프로그램을 작성하라.

입력 형식
입력으로 지도의 한 변 크기 n 과 2개의 정수 배열 arr1, arr2가 들어온다.

1 ≦ n ≦ 16
arr1, arr2는 길이 n인 정수 배열로 주어진다.
정수 배열의 각 원소 x를 이진수로 변환했을 때의 길이는 n 이하이다. 즉, 0 ≦ x ≦ 2n - 1을 만족한다.
출력 형식
원래의 비밀지도를 해독하여 '#', 공백으로 구성된 문자열 배열로 출력하라.

입출력 예제
매개변수	값
n	5
arr1	[9, 20, 28, 18, 11]
arr2	[30, 1, 21, 17, 28]
출력	["#####","# # #", "### #", "# ##", "#####"]
매개변수	값
n	6
arr1	[46, 33, 33 ,22, 31, 50]
arr2	[27 ,56, 19, 14, 14, 10]
출력	["######", "### #", "## ##", " #### ", " #####", "### # "]

In [0]:
n = 5
arr1 = [9, 20, 28, 18, 11]
arr2 = [30, 1, 21, 17, 28]
for a1, a2 in zip (arr1, arr2):
    print(str(bin(a1 | a2))[2:])
    

In [0]:
n=6
arr1 = [46, 33, 33 ,22, 31, 50]
arr2 = [27 ,56, 19, 14, 14, 10] 

for a1, a2 in zip (arr1, arr2):
    tmp str(bin(a1 | a2)[2:])
    tmp = '0'*(n - len(tmp)) + tmp
    tmp = tmp.replace('1', '#')
    tmp = tmp.replace('0', ' ')
    print(tmp)

In [0]:
import numpy as np

In [0]:
array1 = np.array([1,2,3])

In [44]:
array1[1]

2

In [47]:
array2 = np.array([[1,2,3], [4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
array2.shape

(2, 3)

In [50]:
print('array1 : {:0}차원, array2 : {:1} 차원 '.format(array1.ndim, array2.ndim))

array1 : 1차원, array2 : 2 차원 


In [51]:
array = np.arange(5,10)
array

array([5, 6, 7, 8, 9])

In [53]:
zero_array = np.zeros((3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [54]:
array = np.arange(10)
array1 = array.reshape(2, 5)
array2 = array.reshape(5, -1)  # -1 : 열은 알아서 해라는 의미

print(array1)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [66]:
array1 = np.arange(10)
print(array1)
print(array1[1:])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [58]:
original_array = np.array([5,1,3,9])
np_sort = np.sort(original_array)
print(np_sort)
print(original_array)

[1 3 5 9]
[5 1 3 9]


In [60]:
original_array.sort()
print(original_array)

[1 3 5 9]


In [62]:
array = np.array([3,1,5,9])
array_sort = np.sort(array)
array_index = np.argsort(array)
print(array_sort)
print(array_index)

[1 3 5 9]
[1 0 2 3]


In [71]:
#pandas
import pandas as pd

col = ['col1']
array = np.array([1,2,3])
d = pd.DataFrame(array, columns = col)
d

col1
0     1
1     2
2     3